version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./yarn.lock:/opt/node_app/yarn.lock
      - notused:/opt/node_app/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    ports:
      - 5432:5432
    volumes:
      - objection-hashid-investigation-db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev

volumes:
  objection-hashid-investigation-db:
    driver: local
  notused:
